[package]
name = "framebolt"
edition.workspace = true
version.workspace = true

[workspace]
resolver = "2"

members = [
    "crates/framebolt-core",
    "crates/framebolt-gstreamer",
    "crates/framebolt-media",
    "crates/framebolt-canvas",
    "crates/framebolt-egui",
    "platforms/desktop",
    "platforms/android",
    "platforms/ios",
]

[workspace.package]
edition = "2024"
version = "0.1.17"

[workspace.dependencies]
framebolt-core = { path = "crates/framebolt-core" }
framebolt-egui = { path = "crates/framebolt-egui" }
glam = "0.32.1"
eframe = { version = "0.33.3", default-features = false }
egui = "0.33.3"
egui_dock = "0.18.0"
wgpu = "27.0.1"
winit = { version = "0.30.13", default-features = false }

[dependencies]
framebolt-core.workspace = true
framebolt-egui.workspace = true
egui.workspace = true
egui_dock.workspace = true

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
eframe = { workspace = true, features = ["wgpu"] }

[target.'cfg(target_os = "android")'.dependencies]
eframe = { workspace = true, default-features = false, features = ["wgpu", "android-native-activity", "default_fonts",]}

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true