[workspace]
members = [
    "apps/desktop",
    "apps/mobile",
    "crates/framebolt-core", "crates/framebolt-gstreamer", "crates/framebolt-media", "crates/framebolt-canvas", "crates/framebolt-egui/"
    ]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.1"

[workspace.dependencies]
framebolt-core = { path = "crates/framebolt-core" }
wasmtime = "42.0.1"
glam = "0.32.1"
wgpu = "27.0.1"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
