on:
  workflow_call:

jobs:
  build-windows-msi-x64:
    name: Build Windows MSI (x86_64)
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download Windows staging
        uses: actions/download-artifact@v8
        with:
          name: framebolt-windows-staging-x86_64
          path: dist/windows-staging

      - name: Install WiX
        shell: pwsh
        run: |
          dotnet tool install --global wix --version 6.0.2
          wix --version

      - name: Get version
        shell: pwsh
        run: |
          $Version = cargo metadata `
            --format-version 1 `
            --no-deps |
            ConvertFrom-Json |
            Select-Object -ExpandProperty packages |
            Select-Object -First 1 |
            Select-Object -ExpandProperty version

          "FRAMEBOLT_VERSION=$Version" >> $env:GITHUB_ENV

      - name: Build Windows MSI
        shell: pwsh
        run: |
          ./scripts/windows/package_windows_msi.ps1 -Architecture x86_64

      - name: Upload Windows installer artifact
        uses: actions/upload-artifact@v7
        with:
          name: framebolt-windows-msi-x64
          path: dist/*.msi
          if-no-files-found: error