on:
  workflow_call:

jobs:
  build-snap-x64:
    name: Build & Package Snap (x86_64)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Prepare Snap package
        run: |
          ./scripts/linux/init_package_snap.sh

      - name: Build Snap
        uses: canonical/action-build@v1
        id: snapcraft

      - name: Copy Snap to dist
        run: |
          mkdir -p dist
          cp "${{ steps.snapcraft.outputs.snap }}" dist/framebolt-x86_64.snap

      - name: Upload Snap artifact
        uses: actions/upload-artifact@v7
        with:
          name: framebolt-snap-x86_64
          path: dist/*.snap
          if-no-files-found: error